"""Multi-model writing pipeline for essay chapters.

7.6.2026
generated by Claude Code Opus 4.8 (successor to qa_review.py)

WHAT THIS DOES
--------------
For each file given on the command line, three roles run in sequence:

    REVIEW  ->  PLAN  ->  WRITE

  REVIEW  one or more models each read the chapter and return a critique
          (factual errors, logical gaps, style, bias). The critiques are
          merged, with reviewers ANONYMIZED as "Reviewer A / B / C", into
                                                  -> <stem>-comments<ext>
  PLAN    one model reads the chapter + the merged comments and decides,
          point by point, what to accept and what to refute. This is the
          "valuable insights" file and is KEPT (and tracked in git):
                                                  -> <stem>-plan<ext>
  WRITE   one model rewrites the chapter, silently incorporating the points
          it accepts, and OVERWRITES the original in place:
                                                  -> <stem><ext>
          The untouched original is first copied to  <stem>-backup<ext>
          (and is also always recoverable via git).

KEY DESIGN IDEA — ANY MODEL CAN PLAY ANY ROLE
---------------------------------------------
Unlike the old qa_review.py, the roles are NOT hard-wired to specific
providers. A role is just a prompt template; a model is just an entry in the
MODELS registry. You assign models to roles on the command line:

    improve myfile.md --review gemini,mistral --plan openai --write claude

or, relying on the defaults (same configuration as before):

    improve myfile.md

WHY THE TAGS ARE ANONYMIZED
---------------------------
LLMs show "self-preference bias": a model tends to rate its own output more
favorably. The PLAN model sees the merged comments, and you may one day let a
model plan over comments from its own family. Tagging reviewers "A / B / C"
(instead of "Gemini", "OpenAI") removes the cue, so the planner judges the
substance, not the source. The A/B/C -> real-name mapping is printed to the
console for your eyes only; it never reaches any model.

STATELESSNESS (why there is no shared "memory")
-----------------------------------------------
Every API call here is independent. The Messages / Chat-Completions APIs are
stateless: the SDK client object holds your key and connection, NOT a
conversation. Two calls to the same model share nothing unless we resend the
text, which we never do. That is exactly why the roles can fan out in parallel
and why each run produces fresh (non-deterministic) results.

Usage:
    improve bagatelles/history/israel-ext-3.md
    improve --review gemini,openai,mistral --plan claude --write claude FILE...
    improve --dry-run FILE        # print prompts, call no APIs
    improve --no-write FILE       # stop after PLAN; do not touch the original
    improve --no-context FILE     # cold run: drop the author profile + papers
    improve --jobs 2 FILE...      # process up to 2 files at once (rate-limit aware)

Environment (.env is auto-loaded):
    GEMINI_API_KEY     https://aistudio.google.com/apikey
    OPENAI_API_KEY     https://platform.openai.com/api-keys
    MISTRAL_API_KEY    https://console.mistral.ai/api-keys
    ANTHROPIC_API_KEY  https://console.anthropic.com/
"""

import argparse
import concurrent.futures
import pathlib
import shutil
import sys
import time

from dotenv import load_dotenv

load_dotenv()  # read key=value pairs from a local .env file into os.environ


# =========================================================================
# Model registry — one provider adapter per model, behind a uniform call.
# =========================================================================
# Each adapter is a stateless function:  complete(model_id, context, prompt)
# -> str.  `context` is the system prompt (author profile + reference papers,
# or "" when --no-context is given).  SDK imports are LOCAL to each adapter so
# you only need a provider's package installed if you actually use that model.
#
# Every adapter treats an empty `context` as "send no system prompt" rather
# than an empty block, which some providers reject.


def call_gemini(model_id: str, context: str, prompt: str) -> str:
    from google import genai
    from google.genai import types

    client = genai.Client()  # reads GEMINI_API_KEY from the environment
    config = types.GenerateContentConfig(system_instruction=context) if context else None
    response = client.models.generate_content(
        model=model_id, contents=prompt, config=config
    )
    return response.text


def call_openai(model_id: str, context: str, prompt: str) -> str:
    from openai import OpenAI

    client = OpenAI()  # reads OPENAI_API_KEY from the environment
    messages = [{"role": "user", "content": prompt}]
    if context:
        messages.insert(0, {"role": "system", "content": context})
    response = client.chat.completions.create(model=model_id, messages=messages)
    return response.choices[0].message.content


def call_mistral(model_id: str, context: str, prompt: str) -> str:
    import os

    from mistralai import Mistral

    # Unlike the OpenAI/Gemini SDKs, mistralai (v1) does NOT auto-read the
    # MISTRAL_API_KEY env var: Mistral() leaves api_key=None and the request
    # goes out unauthenticated (HTTP 401). Pass the key explicitly.
    client = Mistral(api_key=os.environ["MISTRAL_API_KEY"])
    messages = [{"role": "user", "content": prompt}]
    if context:
        messages.insert(0, {"role": "system", "content": context})
    response = client.chat.complete(model=model_id, messages=messages)
    return response.choices[0].message.content


def call_claude(model_id: str, context: str, prompt: str) -> str:
    import anthropic

    # max_retries lets the SDK ride out transient 429/529 (overloaded) errors
    # with exponential backoff instead of failing the run.
    client = anthropic.Anthropic(max_retries=6)  # reads ANTHROPIC_API_KEY from env
    # cache_control marks the (large) profile+corpus context block as cacheable,
    # so when Claude plays two roles for one chapter (e.g. PLAN then WRITE) the
    # second call reuses the block instead of re-billing ~18k tokens. The cache
    # lives ~5 min, comfortably covering one chapter's run. An empty context
    # (from --no-context) is omitted rather than sent as a block.
    extra = (
        {"system": [{"type": "text", "text": context, "cache_control": {"type": "ephemeral"}}]}
        if context
        else {}
    )
    # WRITE rewrites a whole chapter, so allow plenty of output tokens.
    with client.messages.stream(
        model=model_id,
        max_tokens=32000,
        messages=[{"role": "user", "content": prompt}],
        **extra,
    ) as stream:
        message = stream.get_final_message()
    return next(block.text for block in message.content if block.type == "text")


# name on the command line -> (adapter function, concrete model id).
# Add a model by adding one line here; it can then play ANY role.
MODELS = {
    "gemini":  (call_gemini,  "gemini-3.5-flash"),
    "openai":  (call_openai,  "gpt-5"),
    "mistral": (call_mistral, "mistral-medium-latest"),
    "claude":  (call_claude,  "claude-opus-4-8"),
}


def run_model(name: str, context: str, prompt: str) -> str:
    """Dispatch one prompt to the named model via its adapter."""
    adapter, model_id = MODELS[name]
    return adapter(model_id, context, prompt)


# =========================================================================
# Context (system prompt) — author profile + reference papers, sent to EVERY
# model so it judges/writes in light of who the author is and what he has
# already argued elsewhere. Built once per run; "" when --no-context is given.
# =========================================================================
HERE = pathlib.Path(__file__).parent
PROFILE_PATH = HERE / "johannes_profile.md"
REFERENCE_PATHS = [
    HERE / "bagatelles/literature/9-russell-on-useless-knowledge.md",
    HERE / "bagatelles/philosophy/27-science.md",
    HERE / "bagatelles/philosophy/28-truth.md",
]


def build_context() -> str:
    """Author profile + reference papers, concatenated once per run.

    The papers are framed as established background the model already knows —
    not as material to be reviewed (unless one happens to be the chapter under
    review, in which case the duplication is harmless)."""
    parts = [PROFILE_PATH.read_text()]
    refs = [
        f"===== REFERENCE PAPER: {p.name} =====\n{p.read_text()}"
        for p in REFERENCE_PATHS
    ]
    if refs:
        parts.append(
            "The papers below are written by the author. Treat them as "
            "established background you are already familiar with; do not "
            "review them unless one is the chapter currently under review.\n\n"
            + "\n\n".join(refs)
        )
    return "\n\n".join(parts)


# =========================================================================
# Role prompt templates — one per stage, independent of which model runs it.
# =========================================================================

REVIEW_PROMPT = (
    "Review this chapter for factual errors, logical gaps, stylistic "
    "weaknesses, and biased statements. Be concise.\n\n{chapter}"
)

PLAN_PROMPT = (
    "Below is a chapter followed by merged reviewer comments. For each point "
    "raised, either accept it (explain how you would fix it) or refute it "
    "(explain why it does not hold). Be specific and concise.\n\n"
    "===== CHAPTER =====\n{chapter}\n\n"
    "===== COMMENTS =====\n{comments}\n"
)

WRITE_PROMPT = (
    "Below is a chapter followed by merged reviewer comments. Produce a revised "
    "version of the chapter that incorporates every point you judge to be valid; "
    "silently leave out the points you would refute. Preserve the author's "
    "voice, language, and Markdown structure. Output ONLY the revised chapter "
    "in Markdown — no preamble, no commentary.\n\n"
    "===== CHAPTER =====\n{chapter}\n\n"
    "===== COMMENTS =====\n{comments}\n"
)


# =========================================================================
# Helpers
# =========================================================================

def with_suffix(path: pathlib.Path, suffix: str) -> pathlib.Path:
    """israel-ext-3.md + '-comments' -> israel-ext-3-comments.md (same dir)."""
    return path.with_name(f"{path.stem}{suffix}{path.suffix}")


def _anon_label(index: int) -> str:
    """Anonymous label handed to reviewers in REVIEW order: A, B, C, ..."""
    return f"Reviewer {chr(ord('A') + index)}"


def _fmt_secs(seconds: float) -> str:
    """0.4 -> '0.4s', 73.2 -> '1m13.2s' for human-readable timings."""
    if seconds < 60:
        return f"{seconds:.1f}s"
    minutes, secs = divmod(seconds, 60)
    return f"{int(minutes)}m{secs:04.1f}s"


def merge_comments(reviews: list[tuple[str, str]]) -> str:
    """Merge critiques into one document, ANONYMIZING the authors.

    `reviews` is a list of (real_model_name, critique) in REVIEW order. The
    output tags each section "Reviewer A / B / C" so the PLAN model cannot
    favor (or distrust) a particular provider — see the module docstring on
    self-preference bias. The real-name mapping stays on the console only.
    """
    sections = [
        f"# {_anon_label(i)}\n\n{text.strip()}\n"
        for i, (_name, text) in enumerate(reviews)
    ]
    return "\n---\n\n".join(sections)


# =========================================================================
# Pipeline — REVIEW -> PLAN -> WRITE for a single file
# =========================================================================

def process(
    path: pathlib.Path,
    review_models: list[str],
    plan_model: str,
    write_model: str,
    write: bool,
    dry_run: bool,
    context: str,
) -> None:
    chapter = path.read_text()
    # perf_counter is monotonic and unaffected by clock changes — the right
    # tool for measuring elapsed wall-clock time of each stage.
    t_start = time.perf_counter()

    # --- dry run: show exactly what each role would send, hit no API --------
    if dry_run:
        if context:
            print(
                f"\n===== CONTEXT (all models): profile {PROFILE_PATH.name} + "
                f"{len(REFERENCE_PATHS)} reference paper(s), {len(context):,} "
                f"chars total ====="
            )
        else:
            print("\n===== CONTEXT: none (--no-context) =====")
        for i, name in enumerate(review_models):
            label = _anon_label(i)
            model_id = MODELS[name][1]
            print(f"\n===== [{path.name}] REVIEW -> {name} ({model_id}) as {label} =====")
            print(REVIEW_PROMPT.format(chapter=chapter))
        placeholder = "<merged anonymized comments are inserted here at run time>"
        print(f"\n===== [{path.name}] PLAN -> {plan_model} ({MODELS[plan_model][1]}) =====")
        print(PLAN_PROMPT.format(chapter=chapter, comments=placeholder))
        print(f"\n===== [{path.name}] WRITE -> {write_model} ({MODELS[write_model][1]}) =====")
        print(WRITE_PROMPT.format(chapter=chapter, comments=placeholder))
        return

    # --- 0. Back up the original (once). ------------------------------------
    # Keep the very first original: if a backup already exists (e.g. from an
    # earlier run on this file), do NOT overwrite it with an already-revised
    # version. The backup is for manual diffing and is git-ignored.
    backup_path = with_suffix(path, "-backup")
    if not backup_path.exists():
        shutil.copy2(path, backup_path)
        print(f"  -> {backup_path}  (backup of the original — delete manually)")
    else:
        print(f"  (backup already exists, kept: {backup_path})")

    # --- 1. REVIEW: every reviewer in parallel. -----------------------------
    # A reviewer that raises (bad key, quota, network) is skipped with a
    # warning rather than aborting the run. Results are kept in REVIEW order
    # so the A/B/C labels are stable across runs.
    for name in review_models:
        print(f"[{path.name}] REVIEW: asking {name} ({MODELS[name][1]})...")

    t_review = time.perf_counter()
    critiques: dict[str, str] = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=len(review_models)) as pool:
        # Each future records its own start so we can report per-reviewer time
        # alongside the wall-clock for the whole (parallel) stage.
        starts = {}
        futures = {}
        for name in review_models:
            starts[name] = time.perf_counter()
            futures[pool.submit(run_model, name, context, REVIEW_PROMPT.format(chapter=chapter))] = name
        for future in concurrent.futures.as_completed(futures):
            name = futures[future]
            try:
                critiques[name] = future.result()
                print(f"  [{name}] done in {_fmt_secs(time.perf_counter() - starts[name])}")
            except Exception as exc:  # noqa: BLE001 - keep the run alive
                print(f"  [{name}] FAILED, skipping: {exc}", file=sys.stderr)
    review_secs = time.perf_counter() - t_review

    if not critiques:
        print(f"[{path.name}] all reviewers failed; nothing to do.", file=sys.stderr)
        return

    # Reassemble in request order, then anonymize. Print the mapping so YOU
    # can trace A/B/C back to providers; the models never see it.
    ordered = [(n, critiques[n]) for n in review_models if n in critiques]
    for i, (name, _) in enumerate(ordered):
        print(f"  {_anon_label(i)} = {name}")
    comments = merge_comments(ordered)
    comments_path = with_suffix(path, "-comments")
    comments_path.write_text(comments)
    print(f"  -> {comments_path}  (merged anonymized comments — delete manually)")
    print(f"  REVIEW done in {_fmt_secs(review_secs)}")

    # --- 2. PLAN: accept/refute each point. Kept (tracked in git). ----------
    print(f"[{path.name}] PLAN: asking {plan_model} ({MODELS[plan_model][1]})...")
    t_plan = time.perf_counter()
    plan = run_model(plan_model, context, PLAN_PROMPT.format(chapter=chapter, comments=comments))
    plan_secs = time.perf_counter() - t_plan
    plan_path = with_suffix(path, "-plan")
    plan_path.write_text(plan)
    print(f"  -> {plan_path}  (the plan: accept/refute per point — KEPT)")
    print(f"  PLAN done in {_fmt_secs(plan_secs)}")

    # --- 3. WRITE: rewrite and overwrite the original. ----------------------
    # If WRITE fails, leave the original untouched and report — the backup,
    # comments, and plan are already on disk, so no work is lost.
    if write:
        print(f"[{path.name}] WRITE: asking {write_model} ({MODELS[write_model][1]})...")
        t_write = time.perf_counter()
        try:
            revised = run_model(
                write_model, context, WRITE_PROMPT.format(chapter=chapter, comments=comments)
            )
        except Exception as exc:  # noqa: BLE001 - don't clobber the original on failure
            print(
                f"  [WRITE] FAILED after {_fmt_secs(time.perf_counter() - t_write)}, "
                f"original NOT overwritten: {exc}\n"
                f"      Re-run to retry (comments cached in {comments_path}).",
                file=sys.stderr,
            )
            return
        path.write_text(revised)
        print(f"  -> {path}  (OVERWRITTEN — original in {backup_path} and git)")
        print(f"  WRITE done in {_fmt_secs(time.perf_counter() - t_write)}")
    else:
        print("  (WRITE skipped: --no-write)")

    print(f"[{path.name}] TOTAL {_fmt_secs(time.perf_counter() - t_start)}")


# =========================================================================
# Command line
# =========================================================================

def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        prog="improve",
        description="Multi-model writing pipeline (REVIEW -> PLAN -> WRITE) for "
        "essay chapters. Any model can play any role.",
    )
    parser.add_argument(
        "files", nargs="+", type=pathlib.Path, help="chapter file(s) to improve"
    )
    parser.add_argument(
        "--review",
        default="gemini,openai,mistral",
        help="comma-separated models that produce comments (fan-out); "
        "default: gemini,openai,mistral",
    )
    parser.add_argument(
        "--plan",
        default="claude",
        help="model that accepts/refutes each comment; default: claude",
    )
    parser.add_argument(
        "--write",
        dest="write_model",
        default="claude",
        help="model that rewrites the chapter; default: claude",
    )
    parser.add_argument(
        "--no-write",
        action="store_true",
        help="stop after PLAN; do not overwrite the original file",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print the prompts that would be sent and call no APIs",
    )
    parser.add_argument(
        "--no-context",
        action="store_true",
        help="skip the author profile and reference papers (cold run)",
    )
    parser.add_argument(
        "--jobs",
        type=int,
        default=1,
        help="number of files to process concurrently; keep low to respect "
        "provider rate limits (default: 1)",
    )
    args = parser.parse_args(argv)

    # Resolve and validate every model name against the registry.
    review_models = [m.strip() for m in args.review.split(",") if m.strip()]
    requested = {"--review": review_models, "--plan": [args.plan], "--write": [args.write_model]}
    unknown = sorted(
        {m for names in requested.values() for m in names if m not in MODELS}
    )
    if unknown:
        parser.error(
            f"unknown model(s): {', '.join(unknown)}. "
            f"Available: {', '.join(MODELS)}"
        )
    if not review_models:
        parser.error("--review needs at least one model")
    if args.jobs < 1:
        parser.error("--jobs must be >= 1")

    # Author profile + reference papers, read once; empty under --no-context.
    context = "" if args.no_context else build_context()

    # Process files. --jobs > 1 runs whole-file pipelines concurrently; each
    # file already fans out to several models, so keep --jobs small to avoid
    # tripping requests/tokens-per-minute limits.
    def run_one(path: pathlib.Path) -> None:
        process(
            path,
            review_models=review_models,
            plan_model=args.plan,
            write_model=args.write_model,
            write=not args.no_write,
            dry_run=args.dry_run,
            context=context,
        )

    if args.jobs == 1 or len(args.files) == 1:
        for path in args.files:
            run_one(path)
    else:
        with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as pool:
            list(pool.map(run_one, args.files))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))