"""Multi-reviewer QA pipeline for essay chapters.

6.6.2026
generated by Claude Code Opus 4.8

For each file given on the command line:
  1. Send it to several reviewers (Gemini, OpenAI, optionally Mistral) for QA.
  2. Merge their critiques into one file        -> <stem>-qa<ext>
  3. Ask Claude to:
     (b1) rewrite the chapter incorporating the criticism it accepts, and
          OVERWRITE the original file in place   -> <stem><ext>
          (the previous version is recoverable via git)
     (b2) write a point-by-point response, each point accepted or refuted
                                                 -> <stem>-rev-claude<ext>

Usage:
    python qa_review.py bagatelles/history/israel-ext-3.md
    python qa_review.py --reviewers gemini,openai,mistral FILE...
    python qa_review.py --dry-run FILE        # print prompts, call no APIs
    python qa_review.py --no-overwrite FILE   # skip (b1), keep original intact

Environment (.env is auto-loaded):
    GEMINI_API_KEY     https://aistudio.google.com/apikey
    OPENAI_API_KEY     https://platform.openai.com/api-keys
    MISTRAL_API_KEY    https://console.mistral.ai/api-keys   (only if used)
    ANTHROPIC_API_KEY  https://console.anthropic.com/
"""

import argparse
import concurrent.futures
import pathlib
import sys

from dotenv import load_dotenv

load_dotenv()  # read key=value pairs from a local .env file into os.environ

import anthropic

# Model IDs — adjust to taste; verify they exist on your account before a real run.
CLAUDE_MODEL = "claude-opus-4-8"
GEMINI_MODEL = "gemini-3.1-flash-lite"
OPENAI_MODEL = "gpt-5"
MISTRAL_MODEL = "mistral-medium-latest"

# Persona + background corpus sent as the system prompt to EVERY model, so the
# reviewers and Claude judge each chapter in light of who the author is and the
# papers he wants them to already know. Paths are relative to this script.
HERE = pathlib.Path(__file__).parent
PROFILE_PATH = HERE / "johannes_profile.md"
REFERENCE_PATHS = [
    HERE / "bagatelles/mathematics/calculus.md",
    HERE / "bagatelles/philosophy/27-science.md",
    HERE / "bagatelles/philosophy/ethik-0.md",
]


def build_system_prompt() -> str:
    """Author profile + reference papers, concatenated once per run.

    The papers are framed as established background the model already knows —
    not as material to be reviewed (unless one happens to be the chapter
    under review, in which case the duplication is harmless)."""
    parts = [PROFILE_PATH.read_text()]
    refs = [
        f"===== REFERENCE PAPER: {p.name} =====\n{p.read_text()}"
        for p in REFERENCE_PATHS
    ]
    if refs:
        parts.append(
            "The papers below are written by the author. Treat them as "
            "established background you are already familiar with; do not "
            "review them unless one is the chapter currently under review.\n\n"
            + "\n\n".join(refs)
        )
    return "\n\n".join(parts)


QA_PROMPT = (
    "Review this chapter for factual errors, logical gaps, stylistic "
    "weaknesses, and biased statements. Be concise.\n\n{chapter}"
)

REVISE_PROMPT = (
    "Below is a chapter followed by merged QA reviews from several reviewers. "
    "Produce a revised version of the chapter that incorporates every point of "
    "criticism you judge to be valid; silently leave out the points you would "
    "refute. Preserve the author's voice, language, and Markdown structure. "
    "Output ONLY the revised chapter in Markdown — no preamble, no commentary.\n\n"
    "===== CHAPTER =====\n{chapter}\n\n"
    "===== REVIEWS =====\n{reviews}\n"
)

REVIEW_PROMPT = (
    "Below is a chapter followed by merged QA reviews from several reviewers. "
    "For each point raised, either accept it (explain how you would fix it) or "
    "refute it (explain why it does not hold). Be specific and concise.\n\n"
    "===== CHAPTER =====\n{chapter}\n\n"
    "===== REVIEWS =====\n{reviews}\n"
)


# --- Reviewers ------------------------------------------------------------
# Each reviewer takes the chapter text and returns its critique as a string.
# SDK imports are local so an unused provider's package need not be installed.

# Each reviewer treats an empty `system` (from --no-context) as "no system
# prompt" rather than sending an empty block, which some providers reject.

def review_gemini(chapter: str, system: str) -> str:
    from google import genai
    from google.genai import types

    client = genai.Client()  # reads GEMINI_API_KEY from the environment
    config = types.GenerateContentConfig(system_instruction=system) if system else None
    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=QA_PROMPT.format(chapter=chapter),
        config=config,
    )
    return response.text


def review_openai(chapter: str, system: str) -> str:
    from openai import OpenAI

    client = OpenAI()  # reads OPENAI_API_KEY from the environment
    messages = [{"role": "user", "content": QA_PROMPT.format(chapter=chapter)}]
    if system:
        messages.insert(0, {"role": "system", "content": system})
    response = client.chat.completions.create(model=OPENAI_MODEL, messages=messages)
    return response.choices[0].message.content


def review_mistral(chapter: str, system: str) -> str:
    import os

    from mistralai import Mistral

    # Unlike the OpenAI/Gemini SDKs, mistralai (v1) does NOT auto-read the
    # MISTRAL_API_KEY env var: Mistral() leaves api_key=None and the request
    # goes out unauthenticated (HTTP 401). Pass the key explicitly.
    client = Mistral(api_key=os.environ["MISTRAL_API_KEY"])
    messages = [{"role": "user", "content": QA_PROMPT.format(chapter=chapter)}]
    if system:
        messages.insert(0, {"role": "system", "content": system})
    response = client.chat.complete(model=MISTRAL_MODEL, messages=messages)
    return response.choices[0].message.content


# name -> (review function, model id shown in headers/logs)
REVIEWERS = {
    "gemini": (review_gemini, GEMINI_MODEL),
    "openai": (review_openai, OPENAI_MODEL),
    "mistral": (review_mistral, MISTRAL_MODEL),
}


# --- Helpers --------------------------------------------------------------

def with_suffix(path: pathlib.Path, suffix: str) -> pathlib.Path:
    """israel-ext-3.md + '-qa' -> israel-ext-3-qa.md (same directory)."""
    return path.with_name(f"{path.stem}{suffix}{path.suffix}")


def merge_reviews(reviews: dict[str, str]) -> str:
    sections = [
        f"# QA review by {name} ({REVIEWERS[name][1]})\n\n{text.strip()}\n"
        for name, text in reviews.items()
    ]
    return "\n---\n\n".join(sections)


def ask_claude(prompt: str, system: str, max_tokens: int = 32000) -> str:
    # max_retries lets the SDK ride out transient 429/529 (overloaded) errors
    # with exponential backoff instead of failing the run.
    client = anthropic.Anthropic(max_retries=6)  # reads ANTHROPIC_API_KEY from env
    # cache_control marks the (large) profile+corpus system block as cacheable;
    # the second Claude call (b1 after b2) reuses it instead of re-billing ~18k
    # tokens. The cache lives ~5 min, comfortably covering one chapter's run.
    # An empty system (from --no-context) is omitted rather than sent as a block.
    extra = (
        {"system": [{"type": "text", "text": system, "cache_control": {"type": "ephemeral"}}]}
        if system
        else {}
    )
    with client.messages.stream(
        model=CLAUDE_MODEL,
        max_tokens=max_tokens,
        messages=[{"role": "user", "content": prompt}],
        **extra,
    ) as stream:
        message = stream.get_final_message()
    return next(block.text for block in message.content if block.type == "text")


# --- Pipeline -------------------------------------------------------------

def process(
    path: pathlib.Path,
    reviewer_names: list[str],
    overwrite: bool,
    dry_run: bool,
    system: str,
) -> None:
    chapter = path.read_text()

    if dry_run:
        if system:
            print(
                f"\n===== SYSTEM PROMPT (all models): "
                f"profile {PROFILE_PATH.name} + {len(REFERENCE_PATHS)} reference "
                f"paper(s), {len(system):,} chars total ====="
            )
        else:
            print("\n===== SYSTEM PROMPT: none (--no-context) =====")
        for name in reviewer_names:
            model = REVIEWERS[name][1]
            print(f"\n===== [{path.name}] QA PROMPT -> {name} ({model}) =====")
            print(QA_PROMPT.format(chapter=chapter))
        placeholder = "<merged reviewer critiques are inserted here at run time>"
        print(f"\n===== [{path.name}] CLAUDE REVISE PROMPT (b1, {CLAUDE_MODEL}) =====")
        print(REVISE_PROMPT.format(chapter=chapter, reviews=placeholder))
        print(f"\n===== [{path.name}] CLAUDE REVIEW PROMPT (b2, {CLAUDE_MODEL}) =====")
        print(REVIEW_PROMPT.format(chapter=chapter, reviews=placeholder))
        return

    # 1. Collect critiques from all reviewers in parallel. A reviewer that
    #    raises (bad key, quota, network) is skipped with a warning rather than
    #    aborting the whole run.
    for name in reviewer_names:
        print(f"[{path.name}] asking {name} ({REVIEWERS[name][1]})...")

    reviews: dict[str, str] = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=len(reviewer_names)) as pool:
        futures = {
            pool.submit(REVIEWERS[name][0], chapter, system): name
            for name in reviewer_names
        }
        for future in concurrent.futures.as_completed(futures):
            name = futures[future]
            try:
                reviews[name] = future.result()
                print(f"  [{name}] done")
            except Exception as exc:  # noqa: BLE001 - keep the run alive
                print(f"  [{name}] FAILED, skipping: {exc}", file=sys.stderr)

    if not reviews:
        print(f"[{path.name}] all reviewers failed; nothing to do.", file=sys.stderr)
        return

    # 2. Merge into one file (in the order the reviewers were requested).
    merged = merge_reviews({n: reviews[n] for n in reviewer_names if n in reviews})
    qa_path = with_suffix(path, "-qa")
    qa_path.write_text(merged)
    print(f"  -> {qa_path}  (merged reviews)")

    # b2: point-by-point response (accepted or refuted).
    print(f"[{path.name}] asking Claude for the point-by-point response (b2)...")
    rebuttal = ask_claude(REVIEW_PROMPT.format(chapter=chapter, reviews=merged), system)
    rev_path = with_suffix(path, "-rev-claude")
    rev_path.write_text(rebuttal)
    print(f"  -> {rev_path}  (response to every point)")

    # b1: revised chapter, overwriting the original in place. If Claude fails
    # here, leave the original untouched and report — the merged reviews and
    # the (b2) response are already on disk, so no work is lost.
    if overwrite:
        print(f"[{path.name}] asking Claude for the revised chapter (b1)...")
        try:
            revised = ask_claude(REVISE_PROMPT.format(chapter=chapter, reviews=merged), system)
        except Exception as exc:  # noqa: BLE001 - don't clobber the original on failure
            print(
                f"  [b1] FAILED, original NOT overwritten: {exc}\n"
                f"      Re-run to retry (reviews are cached in {qa_path}).",
                file=sys.stderr,
            )
            return
        path.write_text(revised)
        print(f"  -> {path}  (OVERWRITTEN — recover the old version via git)")
    else:
        print("  (b1 skipped: --no-overwrite)")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Multi-reviewer QA pipeline for essay chapters."
    )
    parser.add_argument(
        "files", nargs="+", type=pathlib.Path, help="chapter file(s) to review"
    )
    parser.add_argument(
        "--reviewers",
        default="gemini, openai, mistral",
        help=f"comma-separated reviewers to run; available: "
        f"{', '.join(REVIEWERS)} (default: gemini, openai, mistral)",
    )
    parser.add_argument(
        "--no-overwrite",
        action="store_true",
        help="skip step (b1); do not overwrite the original file",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print the prompts that would be sent and call no APIs",
    )
    parser.add_argument(
        "--no-context",
        action="store_true",
        help="skip the author profile and reference papers (cold review)",
    )
    args = parser.parse_args(argv)

    reviewer_names = [r.strip() for r in args.reviewers.split(",") if r.strip()]
    unknown = [r for r in reviewer_names if r not in REVIEWERS]
    if unknown:
        parser.error(
            f"unknown reviewer(s): {', '.join(unknown)}. "
            f"Available: {', '.join(REVIEWERS)}"
        )

    # profile + reference papers, read once; empty when --no-context is given
    system = "" if args.no_context else build_system_prompt()

    for path in args.files:
        process(
            path,
            reviewer_names,
            overwrite=not args.no_overwrite,
            dry_run=args.dry_run,
            system=system,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
