# Book settings
title: Bagatelles
author: Johannes Siedersleben
copyright: "2025, Johannes Siedersleben"
logo: westfield2.png

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: off  # Using markdown, not executable notebooks

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: bagatelles.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/johsieders/essays
  path_to_book: bagatelles
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

# Sphinx configuration
sphinx:
  extra_extensions:
    - sphinx_proof
    - sphinx_togglebutton
  config:
    html_theme: sphinx_book_theme
    html_theme_options:
      repository_url: https://github.com/johsieders/essays
      use_repository_button: true
      use_issues_button: true
      use_edit_page_button: true
      home_page_in_toc: true
      show_navbar_depth: 2
      navigation_with_keys: true
      show_prev_next: true
    bibtex_reference_style: author_year
    html_static_path:
      - _static